source 'http://rubygems.org'
gem 'rails', '3.0.1'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'validates_timeliness', '~> 3.0'
gem 'gettext'
#gem 'searchlogic'
gem 'meta_search'
gem 'meta_where'
gem 'authlogic'
gem 'formtastic'
gem 'calendar_date_select', :git => 'http://github.com/paneq/calendar_date_select.git', :branch => 'rails3test'
gem 'bluecloth'
gem 'cornell_netid'
gem 'cornell_ldap', '>= 1.3.1'
gem 'aasm'
gem 'declarative_authorization'
gem 'will_paginate'
gem 'repeated_auto_complete'
gem 'paperclip'
gem 'blind_date', '>= 1.0.0'
gem 'daemons'
gem 'bluecloth', :require => 'bluecloth'
gem 'whenever'

group :development, :test do
  gem 'rspec', '>= 2.0'
  gem 'rspec-rails', ">= 2.0"
  gem 'cucumber'
  gem 'cucumber-rails'
#  gem 'webrat'
#  gem 'webrat', '>=0.7.2.beta.6', :git => 'git://github.com/orangewise/webrat.git'
  gem 'capybara'
  gem 'factory_girl'
  gem 'pickle'
  gem 'email_spec'
  gem 'launchy'
  gem 'test-unit'
  gem 'spork'
end

