source 'http://rubygems.org'
gem 'rails', '3.0.3'
gem 'mysql2'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'capistrano'
gem 'validates_timeliness', '~> 3.0'
gem 'gettext'
gem 'jquery-rails'
gem 'meta_search'
gem 'meta_where'
gem 'authlogic'
gem 'formtastic'
gem 'bluecloth'
gem 'cornell_netid'
gem 'cornell_ldap', '>= 1.3.1'
gem 'aasm'
gem 'declarative_authorization'
gem 'will_paginate'
gem 'paperclip'
gem 'blind_date', '~> 1.0.2'
gem 'daemons'
gem 'bluecloth'
gem 'whenever'
gem 'jquery-rails'
gem 'rails3-jquery-autocomplete'
group :development, :test do
  gem 'rspec', '>= 2.0'
  gem 'rspec-rails', ">= 2.0"
  gem 'cucumber'
#  gem 'cucumber-rails', :git => 'git://github.com/aslakhellesoy/cucumber-rails.git', :branch => 'ae7c956c50fcbe1b0ab3abbaa7ada89aded4accb'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'factory_girl'
  gem 'pickle'
  gem 'email_spec'
  gem 'launchy'
  gem 'test-unit'
  gem 'spork'
end

