development:
  session_secret: f09175c170734f89eb54ce2ce4a0fa4994c96f347e2ed842587dadcdcbcdd7a46de5624dd74685f8cc731e257d6cc772482a3560b878e713c6a91baf2e4e4bae
  defaults:
    authority:
      contact_name: 'Office of the Assemblies'
      contact_email: 'assembly@cornell.edu'
    contact:
      phone: '6072553175'
      fax: '6072552182'
      email: 'assembly@cornell.edu'
      web: 'http://assembly.cornell.edu'
      address_1: '109 Day Hall'
      city: 'Ithaca'
      state: 'NY'
      zip: '14853'
    observer_email: 'staff@assembly.cornell.edu'

test:
  session_secret: f09175c170734f89eb54ce2ce4a0fa4994c96f347e2ed842587dadcdcbcdd7a46de5624dd74685f8cc731e257d6cc772482a3560b878e713c6a91baf2e4e4bae
  defaults:
    authority:
      contact_name: 'The Authority'
      contact_email: 'info@example.org'
    contact:
      phone: '6072553175'
      fax: '6072552182'
      email: 'assembly@cornell.edu'
      web: 'http://assembly.cornell.edu'
      address_1: '109 Day Hall'
      city: 'Ithaca'
      state: 'NY'
      zip: '14853'
    observer_email: 'observer@example.org'

production:
  session_secret: f09175c170734f89eb54ce2ce4a0fa4994c96f347e2ed842587dadcdcbcdd7a46de5624dd74685f8cc731e257d6cc772482a3560b878e713c6a91baf2e4e4bae
  defaults:
    authority:
      contact_name: 'Office of the Assemblies'
      contact_email: 'assembly@cornell.edu'
    contact:
      phone: '6072553175'
      fax: '6072552182'
      email: 'assembly@cornell.edu'
      web: 'http://assembly.cornell.edu'
      address_1: '109 Day Hall'
      city: 'Ithaca'
      state: 'NY'
      zip: '14853'
    observer_email: 'staff@assembly.cornell.edu'

