require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MeetingMotionsController do

  def mock_meeting_motion(stubs={})
    @mock_meeting_motion ||= mock_model(MeetingMotion, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all meeting_motions as @meeting_motions" do
      MeetingMotion.stub(:all) { [mock_meeting_motion] }
      get :index
      assigns(:meeting_motions).should eq([mock_meeting_motion])
    end
  end

  describe "GET show" do
    it "assigns the requested meeting_motion as @meeting_motion" do
      MeetingMotion.stub(:find).with("37") { mock_meeting_motion }
      get :show, :id => "37"
      assigns(:meeting_motion).should be(mock_meeting_motion)
    end
  end

  describe "GET new" do
    it "assigns a new meeting_motion as @meeting_motion" do
      MeetingMotion.stub(:new) { mock_meeting_motion }
      get :new
      assigns(:meeting_motion).should be(mock_meeting_motion)
    end
  end

  describe "GET edit" do
    it "assigns the requested meeting_motion as @meeting_motion" do
      MeetingMotion.stub(:find).with("37") { mock_meeting_motion }
      get :edit, :id => "37"
      assigns(:meeting_motion).should be(mock_meeting_motion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created meeting_motion as @meeting_motion" do
        MeetingMotion.stub(:new).with({'these' => 'params'}) { mock_meeting_motion(:save => true) }
        post :create, :meeting_motion => {'these' => 'params'}
        assigns(:meeting_motion).should be(mock_meeting_motion)
      end

      it "redirects to the created meeting_motion" do
        MeetingMotion.stub(:new) { mock_meeting_motion(:save => true) }
        post :create, :meeting_motion => {}
        response.should redirect_to(meeting_motion_url(mock_meeting_motion))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved meeting_motion as @meeting_motion" do
        MeetingMotion.stub(:new).with({'these' => 'params'}) { mock_meeting_motion(:save => false) }
        post :create, :meeting_motion => {'these' => 'params'}
        assigns(:meeting_motion).should be(mock_meeting_motion)
      end

      it "re-renders the 'new' template" do
        MeetingMotion.stub(:new) { mock_meeting_motion(:save => false) }
        post :create, :meeting_motion => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested meeting_motion" do
        MeetingMotion.stub(:find).with("37") { mock_meeting_motion }
        mock_meeting_motion.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :meeting_motion => {'these' => 'params'}
      end

      it "assigns the requested meeting_motion as @meeting_motion" do
        MeetingMotion.stub(:find) { mock_meeting_motion(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:meeting_motion).should be(mock_meeting_motion)
      end

      it "redirects to the meeting_motion" do
        MeetingMotion.stub(:find) { mock_meeting_motion(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(meeting_motion_url(mock_meeting_motion))
      end
    end

    describe "with invalid params" do
      it "assigns the meeting_motion as @meeting_motion" do
        MeetingMotion.stub(:find) { mock_meeting_motion(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:meeting_motion).should be(mock_meeting_motion)
      end

      it "re-renders the 'edit' template" do
        MeetingMotion.stub(:find) { mock_meeting_motion(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested meeting_motion" do
      MeetingMotion.stub(:find).with("37") { mock_meeting_motion }
      mock_meeting_motion.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the meeting_motions list" do
      MeetingMotion.stub(:find) { mock_meeting_motion }
      delete :destroy, :id => "1"
      response.should redirect_to(meeting_motions_url)
    end
  end

end
